# RT-IoT2022

The RT-IoT2022, a proprietary dataset derived from a real-time IoT infrastructure, is introduced as a comprehensive resource integrating a diverse range of IoT devices and sophisticated network attack methodologies. The mentioned dataset has no missing values.

Read the complete description about the data and the features using the link provided above.

Build a pipeline for the classification task using various classifiers.(Logistic Regression, Decision Tree (ID3, C4.5 and CART) , Naive Bayes Classifier, Support Vector Machine, k-nearest neighbour)

In [1]:
import pandas as pd

dataset = pd.read_csv('/content/drive/MyDrive/Data Mining Lab/RT_IOT2022.csv')
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123117 entries, 0 to 123116
Data columns (total 85 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Unnamed: 0                123117 non-null  int64
 1   id.orig_p                 123117 non-null  int64
 2   id.resp_p                 123117 non-null  int64
 3   proto                     123117 non-null  object
 4   service                   123117 non-null  object
 5   flow_duration             123117 non-null  float64
 6   fwd_pkts_tot              123117 non-null  int64
 7   bwd_pkts_tot              123117 non-null  int64
 8   fwd_data_pkts_tot         123117 non-null  int64
 9   bwd_data_pkts_tot         123117 non-null  int64
 10  fwd_pkts_per_sec          123117 non-null  float64
 11  bwd_pkts_per_sec          123117 non-null  float64
 12  flow_pkts_per_sec         123117 non-null  float64
 13  down_up_ratio             123117 non-null  float64
 14  fwd_header_size_tot       123117 non-null  int64
 15  fwd_header_size_min       123117 non-null  int64
 16  fwd_header_size_max       123117 non-null  int64
 17  bwd_header_size_tot       123117 non-null  int64
 18  bwd_header_size_min       123117 non-null  int64
 19  bwd_header_size_max       123117 non-null  int64
 20  flow_FIN_flag_count       123117 non-null  int64
 21  flow_SYN_flag_count       123117 non-null  int64
 22  flow_RST_flag_count       123117 non-null  int64
 23  fwd_PSH_flag_count        123117 non-null  int64
 24  bwd_PSH_flag_count        123117 non-null  int64
 25  flow_ACK_flag_count       123117 non-null  int64
 26  fwd_URG_flag_count        123117 non-null  int64
 27  bwd_URG_flag_count        123117 non-null  int64
 28  flow_CWR_flag_count       123117 non-null  int64
 29  flow_ECE_flag_count       123117 non-null  int64
 30  fwd_pkts_payload.min      123117 non-null  float64
 31  fwd_pkts_payload.max      123117 non-null  float64
 32  fwd_pkts_payload.tot      123117 non-null  float64
 33  fwd_pkts_payload.avg      123117 non-null  float64
 34  fwd_pkts_payload.std      123117 non-null  float64
 35  bwd_pkts_payload.min      123117 non-null  float64
 36  bwd_pkts_payload.max      123117 non-null  float64
 37  bwd_pkts_payload.tot      123117 non-null  float64
 38  bwd_pkts_payload.avg      123117 non-null  float64
 39  bwd_pkts_payload.std      123117 non-null  float64
 40  flow_pkts_payload.min     123117 non-null  float64
 41  flow_pkts_payload.max     123117 non-null  float64
 42  flow_pkts_payload.tot     123117 non-null  float64
 43  flow_pkts_payload.avg     123117 non-null  float64
 44  flow_pkts_payload.std     123117 non-null  float64
 45  fwd_iat.min               123117 non-null  float64
 46  fwd_iat.max               123117 non-null  float64
 47  fwd_iat.tot               123117 non-null  float64
 48  fwd_iat.avg               123117 non-null  float64
 49  fwd_iat.std               123117 non-null  float64
 50  bwd_iat.min               123117 non-null  float64
 51  bwd_iat.max               123117 non-null  float64
 52  bwd_iat.tot               123117 non-null  float64
 53  bwd_iat.avg               123117 non-null  float64
 54  bwd_iat.std               123117 non-null  float64
 55  flow_iat.min              123117 non-null  float64
 56  flow_iat.max              123117 non-null  float64
 57  flow_iat.tot              123117 non-null  float64
 58  flow_iat.avg              123117 non-null  float64
 59  flow_iat.std              123117 non-null  float64
 60  payload_bytes_per_second  123117 non-null  float64
 61  fwd_subflow_pkts          123117 non-null  float64
 62  bwd_subflow_pkts          123117 non-null  float64
 63  fwd_subflow_bytes         123117 non-null  float64
 64  bwd_subflow_bytes         123117 non-null  float64
 65  fwd_bulk_bytes            123117 non-null  float64
 66  bwd_bulk_bytes            123117 non-null  float64
 67  fwd_bulk_packets          123117 non-null  float64
 68  bwd_bulk_packets          123117 non-null  float64
 69  fwd_bulk_rate             123117 non-null  float64
 70  bwd_bulk_rate             123117 non-null  float64
 71  active.min                123117 non-null  float64
 72  active.max                123117 non-null  float64
 73  active.tot                123117 non-null  float64
 74  active.avg                123117 non-null  float64
 75  active.std                123117 non-null  float64
 76  idle.min                  123117 non-null  float64
 77  idle.max                  123117 non-null  float64
 78  idle.tot                  123117 non-null  float64
 79  idle.avg                  123117 non-null  float64
 80  idle.std                  123117 non-null  float64
 81  fwd_init_window_size      123117 non-null  int64
 82  bwd_init_window_size      123117 non-null  int64
 83  fwd_last_window_size      123117 non-null  int64
 84  Attack_type               123117 non-null  object
dtypes: float64(56), int64(26), object(3)
memory usage: 79.8+ MB

In [2]:
dataset.head()

,Unnamed: 0,id.orig_p,id.resp_p,proto,service,flow_duration,fwd_pkts_tot,bwd_pkts_tot,fwd_data_pkts_tot,bwd_data_pkts_tot,...,active.std,idle.min,idle.max,idle.tot,idle.avg,idle.std,fwd_init_window_size,bwd_init_window_size,fwd_last_window_size,Attack_type
0,0,38667,1883,tcp,mqtt,32.011598,9,5,3,3,...,0.0,2.972918e+07,2.972918e+07,2.972918e+07,2.972918e+07,0.0,64240,26847,502,MQTT_Publish
1,1,51143,1883,tcp,mqtt,31.883584,9,5,3,3,...,0.0,2.985528e+07,2.985528e+07,2.985528e+07,2.985528e+07,0.0,64240,26847,502,MQTT_Publish
2,2,44761,1883,tcp,mqtt,32.124053,9,5,3,3,...,0.0,2.984215e+07,2.984215e+07,2.984215e+07,2.984215e+07,0.0,64240,26847,502,MQTT_Publish
3,3,60893,1883,tcp,mqtt,31.961063,9,5,3,3,...,0.0,2.991377e+07,2.991377e+07,2.991377e+07,2.991377e+07,0.0,64240,26847,502,MQTT_Publish
4,4,51087,1883,tcp,mqtt,31.902362,9,5,3,3,...,0.0,2.981470e+07,2.981470e+07,2.981470e+07,2.981470e+07,0.0,64240,26847,502,MQTT_Publish

In [ ]:
df = dataset.drop(columns=['Unnamed: 0'], axis=1)
target = dataset['Attack_type']

df.head()

,id.orig_p,id.resp_p,proto,service,flow_duration,fwd_pkts_tot,bwd_pkts_tot,fwd_data_pkts_tot,bwd_data_pkts_tot,fwd_pkts_per_sec,...,active.std,idle.min,idle.max,idle.tot,idle.avg,idle.std,fwd_init_window_size,bwd_init_window_size,fwd_last_window_size,Attack_type
0,38667,1883,tcp,mqtt,32.011598,9,5,3,3,0.281148,...,0.0,2.972918e+07,2.972918e+07,2.972918e+07,2.972918e+07,0.0,64240,26847,502,MQTT_Publish
1,51143,1883,tcp,mqtt,31.883584,9,5,3,3,0.282277,...,0.0,2.985528e+07,2.985528e+07,2.985528e+07,2.985528e+07,0.0,64240,26847,502,MQTT_Publish
2,44761,1883,tcp,mqtt,32.124053,9,5,3,3,0.280164,...,0.0,2.984215e+07,2.984215e+07,2.984215e+07,2.984215e+07,0.0,64240,26847,502,MQTT_Publish
3,60893,1883,tcp,mqtt,31.961063,9,5,3,3,0.281593,...,0.0,2.991377e+07,2.991377e+07,2.991377e+07,2.991377e+07,0.0,64240,26847,502,MQTT_Publish
4,51087,1883,tcp,mqtt,31.902362,9,5,3,3,0.282111,...,0.0,2.981470e+07,2.981470e+07,2.981470e+07,2.981470e+07,0.0,64240,26847,502,MQTT_Publish

1. Preprocess the data if duplication of instances are found/ drop the single valued columns

In [ ]:
# Dropping duplictes
df.drop_duplicates(inplace=True)

# dropping single values columns
single_value_columns = [col for col in df.columns if df[col].nunique() == 1]
print("Single values columns: ", single_value_columns)
df.drop(columns=single_value_columns, inplace=True)

df.head()

Single values columns:  ['bwd_URG_flag_count']

,id.orig_p,id.resp_p,proto,service,flow_duration,fwd_pkts_tot,bwd_pkts_tot,fwd_data_pkts_tot,bwd_data_pkts_tot,fwd_pkts_per_sec,...,active.std,idle.min,idle.max,idle.tot,idle.avg,idle.std,fwd_init_window_size,bwd_init_window_size,fwd_last_window_size,Attack_type
0,38667,1883,tcp,mqtt,32.011598,9,5,3,3,0.281148,...,0.0,2.972918e+07,2.972918e+07,2.972918e+07,2.972918e+07,0.0,64240,26847,502,MQTT_Publish
1,51143,1883,tcp,mqtt,31.883584,9,5,3,3,0.282277,...,0.0,2.985528e+07,2.985528e+07,2.985528e+07,2.985528e+07,0.0,64240,26847,502,MQTT_Publish
2,44761,1883,tcp,mqtt,32.124053,9,5,3,3,0.280164,...,0.0,2.984215e+07,2.984215e+07,2.984215e+07,2.984215e+07,0.0,64240,26847,502,MQTT_Publish
3,60893,1883,tcp,mqtt,31.961063,9,5,3,3,0.281593,...,0.0,2.991377e+07,2.991377e+07,2.991377e+07,2.991377e+07,0.0,64240,26847,502,MQTT_Publish
4,51087,1883,tcp,mqtt,31.902362,9,5,3,3,0.282111,...,0.0,2.981470e+07,2.981470e+07,2.981470e+07,2.981470e+07,0.0,64240,26847,502,MQTT_Publish

2. Identify the suitable normalization/discretization technique on features to transform the data

In [ ]:
from sklearn.preprocessing import StandardScaler
import pandas as pd

# Identify categorical columns
categorical_cols = df.select_dtypes(include='object').columns
df_numeric = df.drop(columns=categorical_cols)

# Scale numeric features
scaler = StandardScaler()
df_scaled = pd.DataFrame(
    scaler.fit_transform(df_numeric),
    columns=df_numeric.columns
).reset_index(drop=True)
df_cat = df[categorical_cols].reset_index(drop=True)

df_scaled_concat = pd.concat([df_scaled, df_cat], axis=1)

# drop the target class
df_new = df_scaled_concat.drop(columns=['Attack_type'])
target = df_scaled_concat['Attack_type']
df_new.head()

,id.orig_p,id.resp_p,flow_duration,fwd_pkts_tot,bwd_pkts_tot,fwd_data_pkts_tot,bwd_data_pkts_tot,fwd_pkts_per_sec,bwd_pkts_per_sec,flow_pkts_per_sec,...,idle.min,idle.max,idle.tot,idle.avg,idle.std,fwd_init_window_size,bwd_init_window_size,fwd_last_window_size,proto,service
0,0.196030,0.155128,0.221961,0.303454,0.090645,0.079306,0.065246,-0.947016,-0.946793,-0.946908,...,3.117726,2.959698,0.216062,3.044335,-0.042378,3.069373,2.363506,-0.038155,tcp,mqtt
1,0.853840,0.155128,0.220953,0.303454,0.090645,0.079306,0.065246,-0.947016,-0.946793,-0.946908,...,3.131745,2.973048,0.217102,3.058048,-0.042378,3.069373,2.363506,-0.038155,tcp,mqtt
2,0.517343,0.155128,0.222846,0.303454,0.090645,0.079306,0.065246,-0.947016,-0.946793,-0.946908,...,3.130286,2.971658,0.216994,3.056620,-0.042378,3.069373,2.363506,-0.038155,tcp,mqtt
3,1.367919,0.155128,0.221563,0.303454,0.090645,0.079306,0.065246,-0.947016,-0.946793,-0.946908,...,3.138249,2.979242,0.217584,3.064410,-0.042378,3.069373,2.363506,-0.038155,tcp,mqtt
4,0.850888,0.155128,0.221101,0.303454,0.090645,0.079306,0.065246,-0.947016,-0.946793,-0.946908,...,3.127235,2.968753,0.216767,3.053636,-0.042378,3.069373,2.363506,-0.038155,tcp,mqtt

3. Use Mutual Information and Correlation to select appropriate features. Do they yield similar results?

In [ ]:
# one hot encode the categorical values before finding MI and correlation

categorical_cols = df_new.select_dtypes(include='object').columns
df_encoded_cat = pd.get_dummies(df_new[categorical_cols], drop_first=False).reset_index(drop=True)

df_numeric = df_new.drop(columns=categorical_cols).reset_index(drop=True)
df_encoded = pd.concat([df_numeric, df_encoded_cat], axis=1)

df_encoded.head()

,id.orig_p,id.resp_p,flow_duration,fwd_pkts_tot,bwd_pkts_tot,fwd_data_pkts_tot,bwd_data_pkts_tot,fwd_pkts_per_sec,bwd_pkts_per_sec,flow_pkts_per_sec,...,service_-,service_dhcp,service_dns,service_http,service_irc,service_mqtt,service_ntp,service_radius,service_ssh,service_ssl
0,0.196030,0.155128,0.221961,0.303454,0.090645,0.079306,0.065246,-0.947016,-0.946793,-0.946908,...,False,False,False,False,False,True,False,False,False,False
1,0.853840,0.155128,0.220953,0.303454,0.090645,0.079306,0.065246,-0.947016,-0.946793,-0.946908,...,False,False,False,False,False,True,False,False,False,False
2,0.517343,0.155128,0.222846,0.303454,0.090645,0.079306,0.065246,-0.947016,-0.946793,-0.946908,...,False,False,False,False,False,True,False,False,False,False
3,1.367919,0.155128,0.221563,0.303454,0.090645,0.079306,0.065246,-0.947016,-0.946793,-0.946908,...,False,False,False,False,False,True,False,False,False,False
4,0.850888,0.155128,0.221101,0.303454,0.090645,0.079306,0.065246,-0.947016,-0.946793,-0.946908,...,False,False,False,False,False,True,False,False,False,False

In [ ]:
'''
Mutual information measures the dependence between two variables.
High mutual information means that the features are highly dependent on the target variable.
'''
from sklearn.feature_selection import mutual_info_classif

# Calculate mutual information
mutual_info = mutual_info_classif(df_encoded, target)

# Display mutual information scores for each feature
mutual_info_df = pd.DataFrame({'Feature': df_encoded.columns, 'Mutual Information': mutual_info})
mutual_info_df.sort_values(by='Mutual Information', ascending=False, inplace=True)
print(mutual_info_df)

                  Feature  Mutual Information
38  flow_pkts_payload.tot            0.865382
29   fwd_pkts_payload.avg            0.864357
59      fwd_subflow_bytes            0.863056
27   fwd_pkts_payload.max            0.862962
28   fwd_pkts_payload.tot            0.862373
..                    ...                 ...
91            service_ssh            0.001196
90         service_radius            0.001110
84           service_dhcp            0.000566
25    flow_ECE_flag_count            0.000293
80             proto_icmp            0.000000

[93 rows x 2 columns]

In [ ]:
'''
Correlation can help identify features that are highly correlated.
If two features are highly correlated, one can be dropped.
'''
# Calculate correlation matrix
correlation_matrix = df_encoded.corr().abs()

# Remove highly correlated features (threshold=0.95)
import numpy as np

threshold = 0.95
indices = np.where(correlation_matrix > threshold)
columns_to_drop = set([df_encoded.columns[i] for i, j in zip(*indices) if i < j])

print("Columns to drop: \n", columns_to_drop)

df_corr = df_encoded.drop(columns=columns_to_drop)
df_corr.head()

Columns to drop:
 {'bwd_data_pkts_tot', 'flow_duration', 'bwd_pkts_payload.max', 'active.max', 'flow_pkts_per_sec', 'flow_iat.max', 'bwd_subflow_pkts', 'flow_iat.std', 'bwd_pkts_tot', 'bwd_bulk_bytes', 'idle.min', 'fwd_iat.std', 'fwd_iat.tot', 'bwd_header_size_min', 'bwd_pkts_per_sec', 'fwd_iat.max', 'fwd_bulk_bytes', 'flow_iat.tot', 'idle.max', 'fwd_pkts_per_sec', 'bwd_pkts_payload.tot', 'proto_tcp', 'bwd_header_size_tot'}

,id.orig_p,id.resp_p,fwd_pkts_tot,fwd_data_pkts_tot,down_up_ratio,fwd_header_size_tot,fwd_header_size_min,fwd_header_size_max,bwd_header_size_max,flow_FIN_flag_count,...,service_-,service_dhcp,service_dns,service_http,service_irc,service_mqtt,service_ntp,service_radius,service_ssh,service_ssl
0,0.196030,0.155128,0.303454,0.079306,-0.889348,0.605784,2.271009,2.649994,2.277879,-0.245133,...,False,False,False,False,False,True,False,False,False,False
1,0.853840,0.155128,0.303454,0.079306,-0.889348,0.605784,2.271009,2.649994,2.277879,-0.245133,...,False,False,False,False,False,True,False,False,False,False
2,0.517343,0.155128,0.303454,0.079306,-0.889348,0.605784,2.271009,2.649994,2.277879,-0.245133,...,False,False,False,False,False,True,False,False,False,False
3,1.367919,0.155128,0.303454,0.079306,-0.889348,0.605784,2.271009,2.649994,2.277879,-0.245133,...,False,False,False,False,False,True,False,False,False,False
4,0.850888,0.155128,0.303454,0.079306,-0.889348,0.605784,2.271009,2.649994,2.277879,-0.245133,...,False,False,False,False,False,True,False,False,False,False

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

X = df_encoded
y = target

splits = [(0.7, 0.3), (0.8, 0.2), (0.9, 0.1)]

classifiers = {
    'Logistic Regression': LogisticRegression(),
    'Decision Tree': DecisionTreeClassifier(),
    'Naive Bayes': GaussianNB(),
    'SVM': SVC(),
    'K-Nearest Neighbors': KNeighborsClassifier()
}

def evaluate_model(classifier, X_train, X_test, y_train, y_test):
    model = classifier.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    print(classification_report(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))


for train_size, test_size in splits:
    print("===================================================================================================")
    print(f"Train-Test Split: {train_size*100}% - {test_size*100}%")
    X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=train_size, random_state=42)

    for name, clf in classifiers.items():
        print(f"\nEvaluating {name}...")
        evaluate_model(clf, X_train, X_test, y_train, y_test)

===================================================================================================
Train-Test Split: 70.0% - 30.0%

Evaluating Logistic Regression...

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

                            precision    recall  f1-score   support

            ARP_poisioning       0.90      0.86      0.88      2285
            DDOS_Slowloris       0.94      0.81      0.87       157
             DOS_SYN_Hping       1.00      1.00      1.00     27085
              MQTT_Publish       1.00      1.00      1.00      1263
Metasploit_Brute_Force_SSH       0.70      0.78      0.74         9
             NMAP_FIN_SCAN       1.00      0.86      0.92         7
         NMAP_OS_DETECTION       1.00      1.00      1.00       608
             NMAP_TCP_scan       0.98      1.00      0.99       304
             NMAP_UDP_SCAN       0.94      0.93      0.94       747
       NMAP_XMAS_TREE_SCAN       1.00      1.00      1.00       562
               Thing_Speak       0.88      0.93      0.91      2286
                Wipro_bulb       0.80      0.53      0.64        62

                  accuracy                           0.98     35375
                 macro avg       0.93      0.89      0.91     35375
              weighted avg       0.98      0.98      0.98     35375

[[ 1965     6     0     1     1     0     0     5    16     0   286     5]
 [    5   127     0     0     0     0     0     0    25     0     0     0]
 [    0     0 27085     0     0     0     0     0     0     0     0     0]
 [    2     0     0  1260     0     0     0     0     0     0     1     0]
 [    1     0     0     0     7     0     0     0     0     0     1     0]
 [    1     0     0     0     0     6     0     0     0     0     0     0]
 [    0     0     0     0     0     0   608     0     0     0     0     0]
 [    0     0     0     0     0     0     0   304     0     0     0     0]
 [   47     1     0     0     0     0     0     0   696     0     3     0]
 [    1     0     0     0     0     0     0     0     0   561     0     0]
 [  145     0     0     0     1     0     0     0     1     0  2136     3]
 [   15     1     2     1     1     0     0     1     2     0     6    33]]

Evaluating Decision Tree...
                            precision    recall  f1-score   support

            ARP_poisioning       0.99      0.98      0.99      2285
            DDOS_Slowloris       0.99      0.97      0.98       157
             DOS_SYN_Hping       1.00      1.00      1.00     27085
              MQTT_Publish       1.00      1.00      1.00      1263
Metasploit_Brute_Force_SSH       0.67      0.89      0.76         9
             NMAP_FIN_SCAN       0.86      0.86      0.86         7
         NMAP_OS_DETECTION       1.00      1.00      1.00       608
             NMAP_TCP_scan       1.00      1.00      1.00       304
             NMAP_UDP_SCAN       0.99      0.99      0.99       747
       NMAP_XMAS_TREE_SCAN       1.00      1.00      1.00       562
               Thing_Speak       0.98      0.99      0.99      2286
                Wipro_bulb       0.95      0.87      0.91        62

                  accuracy                           1.00     35375
                 macro avg       0.95      0.96      0.96     35375
              weighted avg       1.00      1.00      1.00     35375

[[ 2248     1     0     2     3     0     0     0     1     0    29     1]
 [    1   153     0     0     0     0     0     0     2     0     1     0]
 [    0     0 27085     0     0     0     0     0     0     0     0     0]
 [    1     1     0  1260     0     0     0     0     0     0     1     0]
 [    1     0     0     0     8     0     0     0     0     0     0     0]
 [    1     0     0     0     0     6     0     0     0     0     0     0]
 [    0     0     0     0     0     0   608     0     0     0     0     0]
 [    0     0     0     0     0     0     0   304     0     0     0     0]
 [    5     0     0     0     1     1     0     0   739     0     1     0]
 [    0     0     0     0     0     0     0     0     1   561     0     0]
 [   18     0     0     0     0     0     0     0     4     0  2262     2]
 [    1     0     1     0     0     0     0     1     0     0     5    54]]

Evaluating Naive Bayes...
                            precision    recall  f1-score   support

            ARP_poisioning       0.97      0.35      0.52      2285
            DDOS_Slowloris       0.16      0.96      0.27       157
             DOS_SYN_Hping       1.00      1.00      1.00     27085
              MQTT_Publish       1.00      0.99      0.99      1263
Metasploit_Brute_Force_SSH       0.01      0.89      0.02         9
             NMAP_FIN_SCAN       0.01      0.86      0.01         7
         NMAP_OS_DETECTION       1.00      1.00      1.00       608
             NMAP_TCP_scan       0.98      1.00      0.99       304
             NMAP_UDP_SCAN       0.52      0.89      0.66       747
       NMAP_XMAS_TREE_SCAN       1.00      1.00      1.00       562
               Thing_Speak       0.73      0.14      0.24      2286
                Wipro_bulb       0.26      0.31      0.28        62

                  accuracy                           0.90     35375
                 macro avg       0.64      0.78      0.58     35375
              weighted avg       0.96      0.90      0.91     35375

[[  811     9     0     0   344   398     0     7   587     0    97    32]
 [    1   151     0     0     2     0     0     0     0     0     1     2]
 [    0     0 27085     0     0     0     0     0     0     0     0     0]
 [    5     0     0  1248     2     0     0     0     1     0     0     7]
 [    0     0     0     0     8     1     0     0     0     0     0     0]
 [    0     0     0     0     1     6     0     0     0     0     0     0]
 [    0     0     0     0     0     0   608     0     0     0     0     0]
 [    0     0     0     0     0     0     0   304     0     0     0     0]
 [    0    47     0     0     3    33     0     0   662     0     0     2]
 [    0     0     0     0     0     1     0     0     0   561     0     0]
 [   17   740     0     0   520   658     0     0    15     0   325    11]
 [    3     0     0     0     2    12     0     0     4     0    22    19]]

Evaluating SVM...
                            precision    recall  f1-score   support

            ARP_poisioning       0.92      0.98      0.95      2285
            DDOS_Slowloris       1.00      0.81      0.89       157
             DOS_SYN_Hping       1.00      1.00      1.00     27085
              MQTT_Publish       1.00      0.99      1.00      1263
Metasploit_Brute_Force_SSH       1.00      0.78      0.88         9
             NMAP_FIN_SCAN       0.75      0.86      0.80         7
         NMAP_OS_DETECTION       1.00      1.00      1.00       608
             NMAP_TCP_scan       0.99      1.00      1.00       304
             NMAP_UDP_SCAN       0.97      0.94      0.95       747
       NMAP_XMAS_TREE_SCAN       1.00      1.00      1.00       562
               Thing_Speak       0.98      0.95      0.96      2286
                Wipro_bulb       1.00      0.52      0.68        62

                  accuracy                           0.99     35375
                 macro avg       0.97      0.90      0.93     35375
              weighted avg       0.99      0.99      0.99     35375

[[ 2246     0     0     0     0     0     0     2     1     0    36     0]
 [    5   127     0     0     0     0     0     0    24     0     1     0]
 [    0     0 27085     0     0     0     0     0     0     0     0     0]
 [    9     0     0  1254     0     0     0     0     0     0     0     0]
 [    2     0     0     0     7     0     0     0     0     0     0     0]
 [    1     0     0     0     0     6     0     0     0     0     0     0]
 [    0     0     0     0     0     0   608     0     0     0     0     0]
 [    0     0     0     0     0     0     0   304     0     0     0     0]
 [   47     0     0     0     0     0     0     0   700     0     0     0]
 [    1     0     0     0     0     0     0     0     0   561     0     0]
 [  112     0     0     0     0     0     0     0     0     0  2174     0]
 [   17     0     0     0     0     2     0     0     0     0    11    32]]

Evaluating K-Nearest Neighbors...
                            precision    recall  f1-score   support

            ARP_poisioning       0.96      0.98      0.97      2285
            DDOS_Slowloris       0.97      0.96      0.96       157
             DOS_SYN_Hping       1.00      1.00      1.00     27085
              MQTT_Publish       1.00      1.00      1.00      1263
Metasploit_Brute_Force_SSH       0.88      0.78      0.82         9
             NMAP_FIN_SCAN       0.75      0.86      0.80         7
         NMAP_OS_DETECTION       1.00      1.00      1.00       608
             NMAP_TCP_scan       0.99      1.00      1.00       304
             NMAP_UDP_SCAN       0.99      0.98      0.99       747
       NMAP_XMAS_TREE_SCAN       1.00      1.00      1.00       562
               Thing_Speak       0.98      0.97      0.98      2286
                Wipro_bulb       0.93      0.68      0.79        62

                  accuracy                           1.00     35375
                 macro avg       0.95      0.93      0.94     35375
              weighted avg       1.00      1.00      1.00     35375

[[ 2228     3     0     0     1     0     0     2     2     0    49     0]
 [    4   150     0     1     0     0     0     0     2     0     0     0]
 [    0     0 27085     0     0     0     0     0     0     0     0     0]
 [    5     0     0  1258     0     0     0     0     0     0     0     0]
 [    1     0     0     0     7     0     0     0     1     0     0     0]
 [    1     0     0     0     0     6     0     0     0     0     0     0]
 [    0     0     0     0     0     0   608     0     0     0     0     0]
 [    0     0     0     0     0     0     0   304     0     0     0     0]
 [   13     0     0     0     0     0     0     0   732     0     1     1]
 [    1     0     0     0     0     0     0     0     0   561     0     0]
 [   55     0     0     0     0     0     0     0     2     0  2227     2]
 [   11     1     0     1     0     2     1     0     0     0     4    42]]
===================================================================================================
Train-Test Split: 80.0% - 20.0%

Evaluating Logistic Regression...

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

                            precision    recall  f1-score   support

            ARP_poisioning       0.89      0.85      0.87      1535
            DDOS_Slowloris       0.89      0.75      0.82       101
             DOS_SYN_Hping       1.00      1.00      1.00     17971
              MQTT_Publish       1.00      1.00      1.00       855
Metasploit_Brute_Force_SSH       0.60      0.75      0.67         4
             NMAP_FIN_SCAN       1.00      0.83      0.91         6
         NMAP_OS_DETECTION       0.99      1.00      1.00       390
             NMAP_TCP_scan       1.00      1.00      1.00       218
             NMAP_UDP_SCAN       0.94      0.94      0.94       526
       NMAP_XMAS_TREE_SCAN       1.00      1.00      1.00       373
               Thing_Speak       0.87      0.93      0.90      1559
                Wipro_bulb       0.93      0.56      0.69        45

                  accuracy                           0.98     23583
                 macro avg       0.93      0.88      0.90     23583
              weighted avg       0.98      0.98      0.98     23583

[[ 1301     8     0     1     1     0     2     1    13     0   207     1]
 [    5    76     0     0     0     0     0     0    20     0     0     0]
 [    0     0 17971     0     0     0     0     0     0     0     0     0]
 [    1     0     1   853     0     0     0     0     0     0     0     0]
 [    1     0     0     0     3     0     0     0     0     0     0     0]
 [    1     0     0     0     0     5     0     0     0     0     0     0]
 [    0     0     0     0     0     0   390     0     0     0     0     0]
 [    0     0     0     0     0     0     0   218     0     0     0     0]
 [   29     0     0     0     0     0     0     0   496     0     1     0]
 [    1     0     0     0     0     0     0     0     0   372     0     0]
 [  108     0     0     0     0     0     0     0     0     0  1450     1]
 [   11     1     1     0     1     0     1     0     1     0     4    25]]

Evaluating Decision Tree...
                            precision    recall  f1-score   support

            ARP_poisioning       0.99      0.99      0.99      1535
            DDOS_Slowloris       1.00      0.94      0.97       101
             DOS_SYN_Hping       1.00      1.00      1.00     17971
              MQTT_Publish       1.00      1.00      1.00       855
Metasploit_Brute_Force_SSH       0.50      1.00      0.67         4
             NMAP_FIN_SCAN       0.83      0.83      0.83         6
         NMAP_OS_DETECTION       1.00      1.00      1.00       390
             NMAP_TCP_scan       1.00      1.00      1.00       218
             NMAP_UDP_SCAN       0.98      0.99      0.98       526
       NMAP_XMAS_TREE_SCAN       1.00      1.00      1.00       373
               Thing_Speak       0.99      0.99      0.99      1559
                Wipro_bulb       0.93      0.87      0.90        45

                  accuracy                           1.00     23583
                 macro avg       0.93      0.97      0.94     23583
              weighted avg       1.00      1.00      1.00     23583

[[ 1512     0     0     0     3     0     0     0     2     0    16     2]
 [    1    95     0     1     0     0     0     0     3     0     1     0]
 [    0     0 17971     0     0     0     0     0     0     0     0     0]
 [    1     0     0   854     0     0     0     0     0     0     0     0]
 [    0     0     0     0     4     0     0     0     0     0     0     0]
 [    1     0     0     0     0     5     0     0     0     0     0     0]
 [    0     0     0     0     0     0   390     0     0     0     0     0]
 [    0     0     0     0     0     0     0   218     0     0     0     0]
 [    4     0     0     0     1     1     0     0   519     0     1     0]
 [    0     0     0     0     0     0     0     0     1   372     0     0]
 [   13     0     0     0     0     0     0     0     3     0  1542     1]
 [    0     0     1     0     0     0     0     1     0     0     4    39]]

Evaluating Naive Bayes...
                            precision    recall  f1-score   support

            ARP_poisioning       0.97      0.36      0.52      1535
            DDOS_Slowloris       0.15      0.94      0.26       101
             DOS_SYN_Hping       1.00      1.00      1.00     17971
              MQTT_Publish       1.00      0.99      0.99       855
Metasploit_Brute_Force_SSH       0.01      0.75      0.01         4
             NMAP_FIN_SCAN       0.01      0.83      0.01         6
         NMAP_OS_DETECTION       1.00      1.00      1.00       390
             NMAP_TCP_scan       0.98      1.00      0.99       218
             NMAP_UDP_SCAN       0.52      0.89      0.66       526
       NMAP_XMAS_TREE_SCAN       1.00      1.00      1.00       373
               Thing_Speak       0.73      0.14      0.24      1559
                Wipro_bulb       0.22      0.29      0.25        45

                  accuracy                           0.90     23583
                 macro avg       0.63      0.77      0.58     23583
              weighted avg       0.96      0.90      0.91     23583

[[  552     9     0     0   210   251     0     5   414     0    68    26]
 [    1    95     0     0     0     0     0     0     0     0     1     4]
 [    0     0 17971     0     0     0     0     0     0     0     0     0]
 [    3     0     0   844     1     0     0     0     1     0     0     6]
 [    0     0     0     0     3     0     0     0     0     0     0     1]
 [    0     0     0     0     1     5     0     0     0     0     0     0]
 [    0     0     0     0     0     0   390     0     0     0     0     0]
 [    0     0     0     0     0     0     0   218     0     0     0     0]
 [    0    31     0     0     2    24     0     0   469     0     0     0]
 [    0     0     0     0     0     1     0     0     0   372     0     0]
 [   13   505     0     0   380   415     0     0    15     0   222     9]
 [    3     0     0     0     2     8     0     0     5     0    14    13]]

Evaluating SVM...
                            precision    recall  f1-score   support

            ARP_poisioning       0.91      0.98      0.95      1535
            DDOS_Slowloris       1.00      0.75      0.86       101
             DOS_SYN_Hping       1.00      1.00      1.00     17971
              MQTT_Publish       1.00      0.99      1.00       855
Metasploit_Brute_Force_SSH       1.00      0.75      0.86         4
             NMAP_FIN_SCAN       0.71      0.83      0.77         6
         NMAP_OS_DETECTION       1.00      1.00      1.00       390
             NMAP_TCP_scan       1.00      1.00      1.00       218
             NMAP_UDP_SCAN       0.96      0.94      0.95       526
       NMAP_XMAS_TREE_SCAN       1.00      1.00      1.00       373
               Thing_Speak       0.98      0.95      0.96      1559
                Wipro_bulb       1.00      0.47      0.64        45

                  accuracy                           0.99     23583
                 macro avg       0.96      0.89      0.91     23583
              weighted avg       0.99      0.99      0.99     23583

[[ 1509     0     0     0     0     0     0     1     1     0    24     0]
 [    5    76     0     0     0     0     0     0    19     0     1     0]
 [    0     0 17971     0     0     0     0     0     0     0     0     0]
 [    6     0     0   849     0     0     0     0     0     0     0     0]
 [    1     0     0     0     3     0     0     0     0     0     0     0]
 [    1     0     0     0     0     5     0     0     0     0     0     0]
 [    0     0     0     0     0     0   390     0     0     0     0     0]
 [    0     0     0     0     0     0     0   218     0     0     0     0]
 [   29     0     0     0     0     0     0     0   497     0     0     0]
 [    1     0     0     0     0     0     0     0     0   372     0     0]
 [   84     0     0     0     0     0     0     0     0     0  1475     0]
 [   15     0     0     0     0     2     0     0     1     0     6    21]]

Evaluating K-Nearest Neighbors...
                            precision    recall  f1-score   support

            ARP_poisioning       0.96      0.98      0.97      1535
            DDOS_Slowloris       0.98      0.94      0.96       101
             DOS_SYN_Hping       1.00      1.00      1.00     17971
              MQTT_Publish       1.00      1.00      1.00       855
Metasploit_Brute_Force_SSH       0.75      0.75      0.75         4
             NMAP_FIN_SCAN       0.71      0.83      0.77         6
         NMAP_OS_DETECTION       1.00      1.00      1.00       390
             NMAP_TCP_scan       1.00      1.00      1.00       218
             NMAP_UDP_SCAN       1.00      0.98      0.99       526
       NMAP_XMAS_TREE_SCAN       1.00      1.00      1.00       373
               Thing_Speak       0.98      0.98      0.98      1559
                Wipro_bulb       0.94      0.64      0.76        45

                  accuracy                           1.00     23583
                 macro avg       0.94      0.93      0.93     23583
              weighted avg       1.00      1.00      1.00     23583

[[ 1503     1     0     0     1     0     0     0     0     0    30     0]
 [    4    95     0     1     0     0     0     0     1     0     0     0]
 [    0     0 17971     0     0     0     0     0     0     0     0     0]
 [    3     0     0   852     0     0     0     0     0     0     0     0]
 [    0     0     0     0     3     0     0     0     1     0     0     0]
 [    1     0     0     0     0     5     0     0     0     0     0     0]
 [    0     0     0     0     0     0   390     0     0     0     0     0]
 [    0     0     0     0     0     0     0   218     0     0     0     0]
 [    7     0     0     0     0     0     0     0   518     0     1     0]
 [    1     0     0     0     0     0     0     0     0   372     0     0]
 [   36     0     0     0     0     0     0     0     0     0  1521     2]
 [    9     1     0     0     0     2     1     0     0     0     3    29]]
===================================================================================================
Train-Test Split: 90.0% - 10.0%

Evaluating Logistic Regression...

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

                            precision    recall  f1-score   support

            ARP_poisioning       0.88      0.86      0.87       773
            DDOS_Slowloris       0.90      0.70      0.79        50
             DOS_SYN_Hping       1.00      1.00      1.00      8949
              MQTT_Publish       1.00      1.00      1.00       439
Metasploit_Brute_Force_SSH       1.00      0.67      0.80         3
             NMAP_FIN_SCAN       1.00      1.00      1.00         4
         NMAP_OS_DETECTION       1.00      1.00      1.00       199
             NMAP_TCP_scan       0.99      1.00      1.00       111
             NMAP_UDP_SCAN       0.94      0.94      0.94       267
       NMAP_XMAS_TREE_SCAN       1.00      0.99      1.00       189
               Thing_Speak       0.88      0.92      0.90       784
                Wipro_bulb       0.88      0.62      0.73        24

                  accuracy                           0.98     11792
                 macro avg       0.96      0.89      0.92     11792
              weighted avg       0.98      0.98      0.98     11792

[[ 668    3    0    1    0    0    0    1    3    0   96    1]
 [   3   35    0    0    0    0    0    0   12    0    0    0]
 [   0    0 8949    0    0    0    0    0    0    0    0    0]
 [   1    0    0  438    0    0    0    0    0    0    0    0]
 [   1    0    0    0    2    0    0    0    0    0    0    0]
 [   0    0    0    0    0    4    0    0    0    0    0    0]
 [   0    0    0    0    0    0  199    0    0    0    0    0]
 [   0    0    0    0    0    0    0  111    0    0    0    0]
 [  16    0    0    0    0    0    0    0  251    0    0    0]
 [   1    0    0    0    0    0    0    0    0  188    0    0]
 [  64    0    0    0    0    0    0    0    0    0  719    1]
 [   5    1    0    0    0    0    0    0    0    0    3   15]]

Evaluating Decision Tree...
                            precision    recall  f1-score   support

            ARP_poisioning       0.98      0.99      0.99       773
            DDOS_Slowloris       1.00      0.96      0.98        50
             DOS_SYN_Hping       1.00      1.00      1.00      8949
              MQTT_Publish       1.00      1.00      1.00       439
Metasploit_Brute_Force_SSH       0.75      1.00      0.86         3
             NMAP_FIN_SCAN       0.80      1.00      0.89         4
         NMAP_OS_DETECTION       1.00      1.00      1.00       199
             NMAP_TCP_scan       0.99      1.00      1.00       111
             NMAP_UDP_SCAN       0.99      0.99      0.99       267
       NMAP_XMAS_TREE_SCAN       1.00      0.99      1.00       189
               Thing_Speak       0.99      0.98      0.99       784
                Wipro_bulb       0.91      0.83      0.87        24

                  accuracy                           1.00     11792
                 macro avg       0.95      0.98      0.96     11792
              weighted avg       1.00      1.00      1.00     11792

[[ 763    0    0    1    0    0    0    0    0    0    8    1]
 [   1   48    0    1    0    0    0    0    0    0    0    0]
 [   0    0 8949    0    0    0    0    0    0    0    0    0]
 [   0    0    0  439    0    0    0    0    0    0    0    0]
 [   0    0    0    0    3    0    0    0    0    0    0    0]
 [   0    0    0    0    0    4    0    0    0    0    0    0]
 [   0    0    0    0    0    0  199    0    0    0    0    0]
 [   0    0    0    0    0    0    0  111    0    0    0    0]
 [   0    0    0    0    1    1    0    0  265    0    0    0]
 [   0    0    0    0    0    0    0    0    1  188    0    0]
 [  10    0    0    0    0    0    0    0    3    0  770    1]
 [   2    0    0    0    0    0    0    1    0    0    1   20]]

Evaluating Naive Bayes...
                            precision    recall  f1-score   support

            ARP_poisioning       0.95      0.36      0.52       773
            DDOS_Slowloris       0.14      0.92      0.24        50
             DOS_SYN_Hping       1.00      1.00      1.00      8949
              MQTT_Publish       1.00      0.99      0.99       439
Metasploit_Brute_Force_SSH       0.01      0.67      0.02         3
             NMAP_FIN_SCAN       0.01      1.00      0.02         4
         NMAP_OS_DETECTION       1.00      1.00      1.00       199
             NMAP_TCP_scan       1.00      1.00      1.00       111
             NMAP_UDP_SCAN       0.51      0.87      0.64       267
       NMAP_XMAS_TREE_SCAN       1.00      0.99      1.00       189
               Thing_Speak       0.78      0.16      0.26       784
                Wipro_bulb       0.21      0.25      0.23        24

                  accuracy                           0.90     11792
                 macro avg       0.63      0.77      0.58     11792
              weighted avg       0.96      0.90      0.91     11792

[[ 275   18    0    0   49  178    0    0  217    0   27    9]
 [   1   46    0    0    0    0    0    0    0    0    0    3]
 [   0    0 8949    0    0    0    0    0    0    0    0    0]
 [   2    0    0  434    0    0    0    0    1    0    0    2]
 [   0    0    0    0    2    0    0    0    0    0    0    1]
 [   0    0    0    0    0    4    0    0    0    0    0    0]
 [   0    0    0    0    0    0  199    0    0    0    0    0]
 [   0    0    0    0    0    0    0  111    0    0    0    0]
 [   0   23    0    0    0   12    0    0  232    0    0    0]
 [   0    0    0    0    0    1    0    0    0  188    0    0]
 [   8  239    0    0  190  211    0    0    7    0  122    7]
 [   3    0    0    0    1    4    0    0    2    0    8    6]]

Evaluating SVM...
                            precision    recall  f1-score   support

            ARP_poisioning       0.90      0.99      0.94       773
            DDOS_Slowloris       1.00      0.70      0.82        50
             DOS_SYN_Hping       1.00      1.00      1.00      8949
              MQTT_Publish       1.00      0.99      1.00       439
Metasploit_Brute_Force_SSH       1.00      0.67      0.80         3
             NMAP_FIN_SCAN       0.80      1.00      0.89         4
         NMAP_OS_DETECTION       1.00      1.00      1.00       199
             NMAP_TCP_scan       0.99      1.00      1.00       111
             NMAP_UDP_SCAN       0.96      0.94      0.95       267
       NMAP_XMAS_TREE_SCAN       1.00      0.99      1.00       189
               Thing_Speak       0.98      0.93      0.96       784
                Wipro_bulb       0.93      0.54      0.68        24

                  accuracy                           0.99     11792
                 macro avg       0.96      0.90      0.92     11792
              weighted avg       0.99      0.99      0.99     11792

[[ 762    0    0    0    0    0    0    1    0    0   10    0]
 [   4   35    0    0    0    0    0    0   11    0    0    0]
 [   0    0 8949    0    0    0    0    0    0    0    0    0]
 [   2    0    0  436    0    0    0    0    0    0    0    1]
 [   1    0    0    0    2    0    0    0    0    0    0    0]
 [   0    0    0    0    0    4    0    0    0    0    0    0]
 [   0    0    0    0    0    0  199    0    0    0    0    0]
 [   0    0    0    0    0    0    0  111    0    0    0    0]
 [  16    0    0    0    0    0    0    0  251    0    0    0]
 [   1    0    0    0    0    0    0    0    0  188    0    0]
 [  51    0    0    0    0    0    0    0    0    0  733    0]
 [   6    0    0    0    0    1    0    0    0    0    4   13]]

Evaluating K-Nearest Neighbors...
                            precision    recall  f1-score   support

            ARP_poisioning       0.96      0.98      0.97       773
            DDOS_Slowloris       0.98      0.92      0.95        50
             DOS_SYN_Hping       1.00      1.00      1.00      8949
              MQTT_Publish       1.00      1.00      1.00       439
Metasploit_Brute_Force_SSH       1.00      0.67      0.80         3
             NMAP_FIN_SCAN       0.80      1.00      0.89         4
         NMAP_OS_DETECTION       1.00      1.00      1.00       199
             NMAP_TCP_scan       1.00      1.00      1.00       111
             NMAP_UDP_SCAN       0.99      0.99      0.99       267
       NMAP_XMAS_TREE_SCAN       1.00      0.99      1.00       189
               Thing_Speak       0.98      0.97      0.98       784
                Wipro_bulb       0.82      0.58      0.68        24

                  accuracy                           1.00     11792
                 macro avg       0.96      0.93      0.94     11792
              weighted avg       1.00      1.00      1.00     11792

[[ 760    0    0    0    0    0    0    0    1    0   11    1]
 [   2   46    0    1    0    0    0    0    1    0    0    0]
 [   0    0 8949    0    0    0    0    0    0    0    0    0]
 [   1    0    0  438    0    0    0    0    0    0    0    0]
 [   0    0    0    0    2    0    0    0    1    0    0    0]
 [   0    0    0    0    0    4    0    0    0    0    0    0]
 [   0    0    0    0    0    0  199    0    0    0    0    0]
 [   0    0    0    0    0    0    0  111    0    0    0    0]
 [   4    0    0    0    0    0    0    0  263    0    0    0]
 [   1    0    0    0    0    0    0    0    0  188    0    0]
 [  20    0    0    0    0    0    0    0    0    0  762    2]
 [   7    1    0    0    0    1    0    0    0    0    1   14]]

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

X = df_encoded
y = target

classifiers = {
    'Logistic Regression': LogisticRegression(),
    'Decision Tree': DecisionTreeClassifier(),
    'Naive Bayes': GaussianNB(),
    'SVM': SVC(),
    'K-Nearest Neighbors': KNeighborsClassifier()
}

def evaluate_model(classifier, X_train, X_test, y_train, y_test):
    model = classifier.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    print(classification_report(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))

In [ ]:
train_size, test_size = 0.7, 0.3
print(f"Train-Test Split: {train_size*100}% - {test_size*100}%")
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=train_size, random_state=42)

for name, clf in classifiers.items():
    print(f"\nEvaluating {name}...")
    evaluate_model(clf, X_train, X_test, y_train, y_test)

Train-Test Split: 70.0% - 30.0%

Evaluating Logistic Regression...

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

                            precision    recall  f1-score   support

            ARP_poisioning       0.94      0.90      0.92      2285
            DDOS_Slowloris       0.98      0.81      0.89       158
             DOS_SYN_Hping       1.00      1.00      1.00     27077
              MQTT_Publish       1.00      1.00      1.00      1263
Metasploit_Brute_Force_SSH       0.90      0.75      0.82        12
             NMAP_FIN_SCAN       0.86      0.75      0.80         8
         NMAP_OS_DETECTION       0.99      1.00      1.00       577
             NMAP_TCP_scan       1.00      1.00      1.00       309
             NMAP_UDP_SCAN       0.96      0.98      0.97       760
       NMAP_XMAS_TREE_SCAN       1.00      1.00      1.00       579
               Thing_Speak       0.90      0.95      0.93      2287
                Wipro_bulb       0.87      0.63      0.73        62

                  accuracy                           0.99     35377
                 macro avg       0.95      0.90      0.92     35377
              weighted avg       0.99      0.99      0.99     35377

[[ 2049     2     0     1     1     0     4     1     2     0   222     3]
 [    3   128     0     0     0     0     0     0    27     0     0     0]
 [    0     0 27077     0     0     0     0     0     0     0     0     0]
 [    2     0     0  1260     0     0     0     0     0     0     1     0]
 [    3     0     0     0     9     0     0     0     0     0     0     0]
 [    2     0     0     0     0     6     0     0     0     0     0     0]
 [    0     0     0     0     0     0   577     0     0     0     0     0]
 [    1     0     0     0     0     0     0   308     0     0     0     0]
 [   12     0     0     0     0     0     0     0   745     0     3     0]
 [    1     0     0     0     0     0     0     0     0   578     0     0]
 [  101     0     0     0     0     0     0     0     2     0  2181     3]
 [    5     0     2     1     0     1     1     0     1     0    12    39]]

Evaluating Decision Tree...
                            precision    recall  f1-score   support

            ARP_poisioning       0.99      0.99      0.99      2285
            DDOS_Slowloris       0.96      0.99      0.98       158
             DOS_SYN_Hping       1.00      1.00      1.00     27077
              MQTT_Publish       1.00      1.00      1.00      1263
Metasploit_Brute_Force_SSH       0.73      0.92      0.81        12
             NMAP_FIN_SCAN       1.00      0.75      0.86         8
         NMAP_OS_DETECTION       1.00      1.00      1.00       577
             NMAP_TCP_scan       1.00      1.00      1.00       309
             NMAP_UDP_SCAN       0.99      0.98      0.99       760
       NMAP_XMAS_TREE_SCAN       1.00      1.00      1.00       579
               Thing_Speak       0.99      0.99      0.99      2287
                Wipro_bulb       0.96      0.85      0.91        62

                  accuracy                           1.00     35377
                 macro avg       0.97      0.96      0.96     35377
              weighted avg       1.00      1.00      1.00     35377

[[ 2253     2     0     0     3     0     0     0     2     0    25     0]
 [    1   157     0     0     0     0     0     0     0     0     0     0]
 [    0     0 27077     0     0     0     0     0     0     0     0     0]
 [    0     2     0  1260     0     0     0     0     0     0     1     0]
 [    1     0     0     0    11     0     0     0     0     0     0     0]
 [    0     0     0     0     0     6     0     0     2     0     0     0]
 [    0     0     0     0     0     0   577     0     0     0     0     0]
 [    0     0     0     0     0     0     0   309     0     0     0     0]
 [    8     0     0     0     1     0     0     0   748     1     2     0]
 [    0     0     0     0     0     0     0     0     1   578     0     0]
 [   23     1     0     1     0     0     0     0     3     0  2257     2]
 [    1     1     1     1     0     0     0     0     0     0     5    53]]

Evaluating Naive Bayes...
                            precision    recall  f1-score   support

            ARP_poisioning       0.98      0.40      0.56      2285
            DDOS_Slowloris       0.38      0.98      0.54       158
             DOS_SYN_Hping       1.00      1.00      1.00     27077
              MQTT_Publish       1.00      1.00      1.00      1263
Metasploit_Brute_Force_SSH       0.01      0.92      0.01        12
             NMAP_FIN_SCAN       0.02      0.75      0.05         8
         NMAP_OS_DETECTION       1.00      1.00      1.00       577
             NMAP_TCP_scan       1.00      1.00      1.00       309
             NMAP_UDP_SCAN       0.53      0.89      0.67       760
       NMAP_XMAS_TREE_SCAN       1.00      1.00      1.00       579
               Thing_Speak       0.68      0.16      0.26      2287
                Wipro_bulb       0.32      0.32      0.32        62

                  accuracy                           0.90     35377
                 macro avg       0.66      0.78      0.62     35377
              weighted avg       0.96      0.90      0.91     35377

[[  908    47     0     0   387   191     0     0   581     0   144    27]
 [    0   155     0     0     1     0     0     0     0     0     0     2]
 [    0     0 27077     0     0     0     0     0     0     0     0     0]
 [    1     0     0  1259     0     0     0     0     1     0     1     1]
 [    1     0     0     0    11     0     0     0     0     0     0     0]
 [    0     0     0     0     2     6     0     0     0     0     0     0]
 [    0     0     0     0     0     0   577     0     0     0     0     0]
 [    0     1     0     0     0     0     0   308     0     0     0     0]
 [    0    41     0     0     6    30     0     0   678     0     2     3]
 [    0     0     0     0     1     0     0     0     0   578     0     0]
 [   19   167     0     0  1705    13     0     0    15     0   359     9]
 [    2     0     0     0    13     1     0     0     4     0    22    20]]

Evaluating SVM...
                            precision    recall  f1-score   support

            ARP_poisioning       0.94      0.99      0.96      2285
            DDOS_Slowloris       1.00      0.81      0.90       158
             DOS_SYN_Hping       1.00      1.00      1.00     27077
              MQTT_Publish       1.00      0.99      1.00      1263
Metasploit_Brute_Force_SSH       1.00      0.75      0.86        12
             NMAP_FIN_SCAN       0.67      0.75      0.71         8
         NMAP_OS_DETECTION       1.00      1.00      1.00       577
             NMAP_TCP_scan       1.00      1.00      1.00       309
             NMAP_UDP_SCAN       0.96      0.98      0.97       760
       NMAP_XMAS_TREE_SCAN       1.00      1.00      1.00       579
               Thing_Speak       0.98      0.96      0.97      2287
                Wipro_bulb       1.00      0.47      0.64        62

                  accuracy                           0.99     35377
                 macro avg       0.96      0.89      0.92     35377
              weighted avg       0.99      0.99      0.99     35377

[[ 2255     0     0     0     0     0     0     1     0     0    29     0]
 [    3   128     0     0     0     0     0     0    27     0     0     0]
 [    0     0 27077     0     0     0     0     0     0     0     0     0]
 [    9     0     0  1253     0     1     0     0     0     0     0     0]
 [    3     0     0     0     9     0     0     0     0     0     0     0]
 [    2     0     0     0     0     6     0     0     0     0     0     0]
 [    0     0     0     0     0     0   577     0     0     0     0     0]
 [    1     0     0     0     0     0     0   308     0     0     0     0]
 [   15     0     0     0     0     0     0     0   744     0     1     0]
 [    1     0     0     0     0     0     0     0     0   578     0     0]
 [   90     0     0     0     0     0     0     0     0     0  2197     0]
 [   15     0     0     0     0     2     0     0     1     0    15    29]]

Evaluating K-Nearest Neighbors...
                            precision    recall  f1-score   support

            ARP_poisioning       0.96      0.98      0.97      2285
            DDOS_Slowloris       0.99      0.96      0.98       158
             DOS_SYN_Hping       1.00      1.00      1.00     27077
              MQTT_Publish       1.00      1.00      1.00      1263
Metasploit_Brute_Force_SSH       1.00      0.75      0.86        12
             NMAP_FIN_SCAN       0.75      0.75      0.75         8
         NMAP_OS_DETECTION       1.00      1.00      1.00       577
             NMAP_TCP_scan       1.00      1.00      1.00       309
             NMAP_UDP_SCAN       0.99      0.98      0.99       760
       NMAP_XMAS_TREE_SCAN       1.00      1.00      1.00       579
               Thing_Speak       0.98      0.97      0.98      2287
                Wipro_bulb       0.95      0.68      0.79        62

                  accuracy                           1.00     35377
                 macro avg       0.97      0.92      0.94     35377
              weighted avg       1.00      1.00      1.00     35377

[[ 2247     0     0     0     0     0     0     0     0     0    38     0]
 [    2   152     0     0     0     0     0     0     4     0     0     0]
 [    0     0 27077     0     0     0     0     0     0     0     0     0]
 [    5     0     0  1258     0     0     0     0     0     0     0     0]
 [    2     0     0     0     9     0     0     0     1     0     0     0]
 [    2     0     0     0     0     6     0     0     0     0     0     0]
 [    0     0     0     0     0     0   577     0     0     0     0     0]
 [    1     0     0     0     0     0     0   308     0     0     0     0]
 [   11     0     0     0     0     0     0     0   748     0     1     0]
 [    1     0     0     0     0     0     0     0     0   578     0     0]
 [   54     0     0     0     0     0     0     0     3     0  2228     2]
 [   11     1     0     1     0     2     0     0     1     0     4    42]]

In [ ]:
train_size, test_size = 0.8, 0.2
print(f"Train-Test Split: {train_size*100}% - {test_size*100}%")
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=train_size, random_state=42)

for name, clf in classifiers.items():
    print(f"\nEvaluating {name}...")
    evaluate_model(clf, X_train, X_test, y_train, y_test)

Train-Test Split: 80.0% - 20.0%

Evaluating Logistic Regression...

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

                            precision    recall  f1-score   support

            ARP_poisioning       0.94      0.93      0.93      1535
            DDOS_Slowloris       0.97      0.75      0.85       102
             DOS_SYN_Hping       1.00      1.00      1.00     18020
              MQTT_Publish       1.00      1.00      1.00       855
Metasploit_Brute_Force_SSH       0.83      0.71      0.77         7
             NMAP_FIN_SCAN       0.75      0.75      0.75         4
         NMAP_OS_DETECTION       0.99      1.00      1.00       377
             NMAP_TCP_scan       1.00      1.00      1.00       216
             NMAP_UDP_SCAN       0.95      0.98      0.97       499
       NMAP_XMAS_TREE_SCAN       1.00      1.00      1.00       366
               Thing_Speak       0.93      0.96      0.94      1559
                Wipro_bulb       0.90      0.62      0.74        45

                  accuracy                           0.99     23585
                 macro avg       0.94      0.89      0.91     23585
              weighted avg       0.99      0.99      0.99     23585

[[ 1420     2     0     1     1     0     3     0     0     0   105     3]
 [    3    77     0     0     0     0     0     0    22     0     0     0]
 [    0     0 18020     0     0     0     0     0     0     0     0     0]
 [    1     0     0   854     0     0     0     0     0     0     0     0]
 [    2     0     0     0     5     0     0     0     0     0     0     0]
 [    1     0     0     0     0     3     0     0     0     0     0     0]
 [    0     0     0     0     0     0   377     0     0     0     0     0]
 [    1     0     0     0     0     0     0   215     0     0     0     0]
 [    7     0     0     0     0     0     0     0   490     0     2     0]
 [    0     0     0     0     0     0     0     0     0   366     0     0]
 [   66     0     0     0     0     0     0     0     3     0  1490     0]
 [    2     0     2     0     0     1     0     1     0     0    11    28]]

Evaluating Decision Tree...
                            precision    recall  f1-score   support

            ARP_poisioning       0.98      0.99      0.98      1535
            DDOS_Slowloris       1.00      0.98      0.99       102
             DOS_SYN_Hping       1.00      1.00      1.00     18020
              MQTT_Publish       0.99      1.00      1.00       855
Metasploit_Brute_Force_SSH       0.67      0.86      0.75         7
             NMAP_FIN_SCAN       1.00      0.75      0.86         4
         NMAP_OS_DETECTION       1.00      1.00      1.00       377
             NMAP_TCP_scan       1.00      1.00      1.00       216
             NMAP_UDP_SCAN       0.99      0.99      0.99       499
       NMAP_XMAS_TREE_SCAN       0.99      1.00      1.00       366
               Thing_Speak       0.99      0.98      0.99      1559
                Wipro_bulb       0.93      0.82      0.87        45

                  accuracy                           1.00     23585
                 macro avg       0.96      0.95      0.95     23585
              weighted avg       1.00      1.00      1.00     23585

[[ 1515     0     0     0     2     0     0     0     2     0    15     1]
 [    1   100     0     1     0     0     0     0     0     0     0     0]
 [    0     0 18020     0     0     0     0     0     0     0     0     0]
 [    0     0     0   855     0     0     0     0     0     0     0     0]
 [    1     0     0     0     6     0     0     0     0     0     0     0]
 [    0     0     0     0     0     3     0     0     0     1     0     0]
 [    0     0     0     0     0     0   377     0     0     0     0     0]
 [    0     0     0     0     0     0     0   216     0     0     0     0]
 [    4     0     0     0     1     0     0     0   492     1     1     0]
 [    0     0     0     0     0     0     0     0     0   366     0     0]
 [   21     0     0     1     0     0     0     0     2     0  1533     2]
 [    0     0     1     3     0     0     0     0     0     0     4    37]]

Evaluating Naive Bayes...
                            precision    recall  f1-score   support

            ARP_poisioning       0.97      0.41      0.58      1535
            DDOS_Slowloris       0.18      0.97      0.31       102
             DOS_SYN_Hping       1.00      1.00      1.00     18020
              MQTT_Publish       1.00      1.00      1.00       855
Metasploit_Brute_Force_SSH       0.01      0.86      0.02         7
             NMAP_FIN_SCAN       0.00      0.75      0.01         4
         NMAP_OS_DETECTION       1.00      1.00      1.00       377
             NMAP_TCP_scan       1.00      1.00      1.00       216
             NMAP_UDP_SCAN       0.53      0.90      0.66       499
       NMAP_XMAS_TREE_SCAN       1.00      1.00      1.00       366
               Thing_Speak       0.70      0.16      0.26      1559
                Wipro_bulb       0.26      0.33      0.29        45

                  accuracy                           0.90     23585
                 macro avg       0.64      0.78      0.59     23585
              weighted avg       0.96      0.90      0.91     23585

[[  627    16     0     0   103   283     0     0   387     0    91    28]
 [    0    99     0     0     1     0     0     0     0     0     0     2]
 [    0     0 18020     0     0     0     0     0     0     0     0     0]
 [    1     0     0   853     0     0     0     0     1     0     0     0]
 [    1     0     0     0     6     0     0     0     0     0     0     0]
 [    0     0     0     0     1     3     0     0     0     0     0     0]
 [    0     0     0     0     0     0   377     0     0     0     0     0]
 [    0     1     0     0     0     0     0   215     0     0     0     0]
 [    0    25     0     0     1    22     0     0   448     0     1     2]
 [    0     0     0     0     0     0     0     0     0   366     0     0]
 [   14   404     0     0   400   472     0     0     9     0   250    10]
 [    1     0     0     0     9     1     0     0     4     0    15    15]]

Evaluating SVM...
                            precision    recall  f1-score   support

            ARP_poisioning       0.94      0.99      0.96      1535
            DDOS_Slowloris       1.00      0.75      0.86       102
             DOS_SYN_Hping       1.00      1.00      1.00     18020
              MQTT_Publish       1.00      0.99      1.00       855
Metasploit_Brute_Force_SSH       1.00      0.71      0.83         7
             NMAP_FIN_SCAN       0.50      0.75      0.60         4
         NMAP_OS_DETECTION       1.00      1.00      1.00       377
             NMAP_TCP_scan       1.00      1.00      1.00       216
             NMAP_UDP_SCAN       0.96      0.98      0.97       499
       NMAP_XMAS_TREE_SCAN       1.00      1.00      1.00       366
               Thing_Speak       0.98      0.96      0.97      1559
                Wipro_bulb       1.00      0.44      0.62        45

                  accuracy                           0.99     23585
                 macro avg       0.95      0.88      0.90     23585
              weighted avg       0.99      0.99      0.99     23585

[[ 1516     0     0     0     0     0     0     0     0     0    19     0]
 [    3    77     0     0     0     0     0     0    22     0     0     0]
 [    0     0 18020     0     0     0     0     0     0     0     0     0]
 [    6     0     0   848     0     1     0     0     0     0     0     0]
 [    2     0     0     0     5     0     0     0     0     0     0     0]
 [    1     0     0     0     0     3     0     0     0     0     0     0]
 [    0     0     0     0     0     0   377     0     0     0     0     0]
 [    1     0     0     0     0     0     0   215     0     0     0     0]
 [    8     0     0     0     0     0     0     0   490     0     1     0]
 [    0     0     0     0     0     0     0     0     0   366     0     0]
 [   64     0     0     0     0     0     0     0     0     0  1495     0]
 [   14     0     0     0     0     2     0     0     1     0     8    20]]

Evaluating K-Nearest Neighbors...
                            precision    recall  f1-score   support

            ARP_poisioning       0.96      0.99      0.97      1535
            DDOS_Slowloris       0.99      0.96      0.98       102
             DOS_SYN_Hping       1.00      1.00      1.00     18020
              MQTT_Publish       1.00      1.00      1.00       855
Metasploit_Brute_Force_SSH       1.00      0.71      0.83         7
             NMAP_FIN_SCAN       0.60      0.75      0.67         4
         NMAP_OS_DETECTION       1.00      1.00      1.00       377
             NMAP_TCP_scan       1.00      1.00      1.00       216
             NMAP_UDP_SCAN       0.99      0.99      0.99       499
       NMAP_XMAS_TREE_SCAN       1.00      1.00      1.00       366
               Thing_Speak       0.98      0.97      0.98      1559
                Wipro_bulb       0.94      0.64      0.76        45

                  accuracy                           1.00     23585
                 macro avg       0.96      0.92      0.93     23585
              weighted avg       1.00      1.00      1.00     23585

[[ 1514     0     0     0     0     0     0     0     0     0    21     0]
 [    2    98     0     0     0     0     0     0     2     0     0     0]
 [    0     0 18020     0     0     0     0     0     0     0     0     0]
 [    3     0     0   852     0     0     0     0     0     0     0     0]
 [    1     0     0     0     5     0     0     0     1     0     0     0]
 [    1     0     0     0     0     3     0     0     0     0     0     0]
 [    0     0     0     0     0     0   377     0     0     0     0     0]
 [    1     0     0     0     0     0     0   215     0     0     0     0]
 [    6     0     0     0     0     0     0     0   492     0     1     0]
 [    0     0     0     0     0     0     0     0     0   366     0     0]
 [   37     0     0     0     0     0     0     0     1     0  1519     2]
 [   10     1     0     0     0     2     0     0     1     0     2    29]]

In [ ]:
train_size, test_size = 0.9, 0.1
print(f"Train-Test Split: {train_size*100}% - {test_size*100}%")
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=train_size, random_state=42)

for name, clf in classifiers.items():
    print(f"\nEvaluating {name}...")
    evaluate_model(clf, X_train, X_test, y_train, y_test)

Train-Test Split: 90.0% - 10.0%

Evaluating Logistic Regression...

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

                            precision    recall  f1-score   support

            ARP_poisioning       0.94      0.93      0.93       773
            DDOS_Slowloris       0.97      0.72      0.83        50
             DOS_SYN_Hping       1.00      1.00      1.00      8983
              MQTT_Publish       0.99      1.00      1.00       439
Metasploit_Brute_Force_SSH       1.00      0.50      0.67         2
             NMAP_FIN_SCAN       0.75      0.75      0.75         4
         NMAP_OS_DETECTION       1.00      1.00      1.00       199
             NMAP_TCP_scan       1.00      1.00      1.00       120
             NMAP_UDP_SCAN       0.93      0.99      0.96       238
       NMAP_XMAS_TREE_SCAN       1.00      1.00      1.00       177
               Thing_Speak       0.93      0.95      0.94       784
                Wipro_bulb       0.88      0.62      0.73        24

                  accuracy                           0.99     11793
                 macro avg       0.95      0.87      0.90     11793
              weighted avg       0.99      0.99      0.99     11793

[[ 716    1    0    3    0    0    0    0    0    0   51    2]
 [   1   36    0    0    0    0    0    0   13    0    0    0]
 [   0    0 8983    0    0    0    0    0    0    0    0    0]
 [   1    0    0  438    0    0    0    0    0    0    0    0]
 [   1    0    0    0    1    0    0    0    0    0    0    0]
 [   1    0    0    0    0    3    0    0    0    0    0    0]
 [   0    0    0    0    0    0  199    0    0    0    0    0]
 [   0    0    0    0    0    0    0  120    0    0    0    0]
 [   3    0    0    0    0    0    0    0  235    0    0    0]
 [   0    0    0    0    0    0    0    0    0  177    0    0]
 [  39    0    0    0    0    0    0    0    4    0  741    0]
 [   2    0    2    0    0    1    0    0    0    0    4   15]]

Evaluating Decision Tree...
                            precision    recall  f1-score   support

            ARP_poisioning       0.98      0.99      0.99       773
            DDOS_Slowloris       1.00      1.00      1.00        50
             DOS_SYN_Hping       1.00      1.00      1.00      8983
              MQTT_Publish       1.00      1.00      1.00       439
Metasploit_Brute_Force_SSH       0.50      0.50      0.50         2
             NMAP_FIN_SCAN       1.00      0.75      0.86         4
         NMAP_OS_DETECTION       0.99      1.00      1.00       199
             NMAP_TCP_scan       1.00      1.00      1.00       120
             NMAP_UDP_SCAN       0.98      0.99      0.99       238
       NMAP_XMAS_TREE_SCAN       1.00      1.00      1.00       177
               Thing_Speak       0.99      0.98      0.99       784
                Wipro_bulb       0.95      0.83      0.89        24

                  accuracy                           1.00     11793
                 macro avg       0.95      0.92      0.93     11793
              weighted avg       1.00      1.00      1.00     11793

[[ 767    0    0    0    1    0    0    0    1    0    4    0]
 [   0   50    0    0    0    0    0    0    0    0    0    0]
 [   0    0 8983    0    0    0    0    0    0    0    0    0]
 [   0    0    0  439    0    0    0    0    0    0    0    0]
 [   1    0    0    0    1    0    0    0    0    0    0    0]
 [   0    0    0    0    0    3    0    0    1    0    0    0]
 [   0    0    0    0    0    0  199    0    0    0    0    0]
 [   0    0    0    0    0    0    0  120    0    0    0    0]
 [   2    0    0    0    0    0    0    0  236    0    0    0]
 [   0    0    0    0    0    0    0    0    0  177    0    0]
 [  12    0    0    0    0    0    0    0    3    0  768    1]
 [   1    0    0    1    0    0    1    0    0    0    1   20]]

Evaluating Naive Bayes...
                            precision    recall  f1-score   support

            ARP_poisioning       0.97      0.42      0.58       773
            DDOS_Slowloris       0.16      0.98      0.27        50
             DOS_SYN_Hping       1.00      1.00      1.00      8983
              MQTT_Publish       1.00      1.00      1.00       439
Metasploit_Brute_Force_SSH       0.00      0.50      0.01         2
             NMAP_FIN_SCAN       0.01      0.75      0.02         4
         NMAP_OS_DETECTION       1.00      1.00      1.00       199
             NMAP_TCP_scan       1.00      1.00      1.00       120
             NMAP_UDP_SCAN       0.51      0.89      0.65       238
       NMAP_XMAS_TREE_SCAN       1.00      1.00      1.00       177
               Thing_Speak       0.74      0.17      0.28       784
                Wipro_bulb       0.27      0.29      0.28        24

                  accuracy                           0.90     11793
                 macro avg       0.64      0.75      0.59     11793
              weighted avg       0.97      0.90      0.91     11793

[[ 322   14    0    0   54  139    0    0  194    0   40   10]
 [   0   49    0    0    0    0    0    0    0    0    0    1]
 [   0    0 8983    0    0    0    0    0    0    0    0    0]
 [   1    0    0  437    0    0    0    0    1    0    0    0]
 [   1    0    0    0    1    0    0    0    0    0    0    0]
 [   0    0    0    0    1    3    0    0    0    0    0    0]
 [   0    0    0    0    0    0  199    0    0    0    0    0]
 [   0    0    0    0    0    0    0  120    0    0    0    0]
 [   0   11    0    0    0   13    0    0  213    0    0    1]
 [   0    0    0    0    0    0    0    0    0  177    0    0]
 [   7  233    0    0  168  226    0    0    6    0  137    7]
 [   2    0    0    0    4    1    0    0    2    0    8    7]]

Evaluating SVM...
                            precision    recall  f1-score   support

            ARP_poisioning       0.94      0.99      0.96       773
            DDOS_Slowloris       1.00      0.72      0.84        50
             DOS_SYN_Hping       1.00      1.00      1.00      8983
              MQTT_Publish       1.00      0.99      1.00       439
Metasploit_Brute_Force_SSH       1.00      0.50      0.67         2
             NMAP_FIN_SCAN       0.60      0.75      0.67         4
         NMAP_OS_DETECTION       1.00      1.00      1.00       199
             NMAP_TCP_scan       1.00      1.00      1.00       120
             NMAP_UDP_SCAN       0.94      0.99      0.97       238
       NMAP_XMAS_TREE_SCAN       1.00      1.00      1.00       177
               Thing_Speak       0.98      0.95      0.97       784
                Wipro_bulb       1.00      0.50      0.67        24

                  accuracy                           0.99     11793
                 macro avg       0.96      0.87      0.89     11793
              weighted avg       0.99      0.99      0.99     11793

[[ 765    0    0    0    0    0    0    0    0    0    8    0]
 [   1   36    0    0    0    0    0    0   13    0    0    0]
 [   0    0 8983    0    0    0    0    0    0    0    0    0]
 [   2    0    0  436    0    1    0    0    0    0    0    0]
 [   1    0    0    0    1    0    0    0    0    0    0    0]
 [   1    0    0    0    0    3    0    0    0    0    0    0]
 [   0    0    0    0    0    0  199    0    0    0    0    0]
 [   0    0    0    0    0    0    0  120    0    0    0    0]
 [   3    0    0    0    0    0    0    0  235    0    0    0]
 [   0    0    0    0    0    0    0    0    0  177    0    0]
 [  38    0    0    0    0    0    0    0    1    0  745    0]
 [   6    0    0    0    0    1    0    0    0    0    5   12]]

Evaluating K-Nearest Neighbors...
                            precision    recall  f1-score   support

            ARP_poisioning       0.96      0.99      0.98       773
            DDOS_Slowloris       0.96      0.96      0.96        50
             DOS_SYN_Hping       1.00      1.00      1.00      8983
              MQTT_Publish       1.00      1.00      1.00       439
Metasploit_Brute_Force_SSH       1.00      0.50      0.67         2
             NMAP_FIN_SCAN       0.75      0.75      0.75         4
         NMAP_OS_DETECTION       1.00      1.00      1.00       199
             NMAP_TCP_scan       1.00      1.00      1.00       120
             NMAP_UDP_SCAN       0.99      0.99      0.99       238
       NMAP_XMAS_TREE_SCAN       1.00      1.00      1.00       177
               Thing_Speak       0.99      0.97      0.98       784
                Wipro_bulb       0.88      0.58      0.70        24

                  accuracy                           1.00     11793
                 macro avg       0.96      0.90      0.92     11793
              weighted avg       1.00      1.00      1.00     11793

[[ 765    0    0    0    0    0    0    0    1    0    7    0]
 [   1   48    0    0    0    0    0    0    1    0    0    0]
 [   0    0 8983    0    0    0    0    0    0    0    0    0]
 [   1    0    0  438    0    0    0    0    0    0    0    0]
 [   1    0    0    0    1    0    0    0    0    0    0    0]
 [   1    0    0    0    0    3    0    0    0    0    0    0]
 [   0    0    0    0    0    0  199    0    0    0    0    0]
 [   0    0    0    0    0    0    0  120    0    0    0    0]
 [   1    1    0    0    0    0    0    0  236    0    0    0]
 [   0    0    0    0    0    0    0    0    0  177    0    0]
 [  19    0    0    0    0    0    0    0    1    0  762    2]
 [   7    1    0    0    0    1    0    0    0    0    1   14]]

In [ ]:
from sklearn.model_selection import GridSearchCV

# Example for Logistic Regression
param_grid = {'C': [0.1, 1, 10], 'solver': ['lbfgs', 'liblinear']}
grid_search = GridSearchCV(LogisticRegression(), param_grid, cv=5)
grid_search.fit(X_train, y_train)
print("Best Parameters for Logistic Regression:", grid_search.best_params_)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

KeyboardInterrupt:

# Iris

Build a pipeline for the classification task using various classifiers.(Logistic Regression, Decision Tree
(ID3, C4.5 and CART) , Naive Bayes Classifier, Support Vector Machine, k-nearest neighbour )
1. Preprocess the data if duplication of instances are found/ drop the single valued columns
2. Identify the suitable normalization/discretization technique on features to transform the
data
3. Use Mutual Information and Correlation to select appropriate features. Do they yield
similar results?
4. Build classification models to classify using the mentioned
classifiers (consider train-test split - 70-30, 80-20 and 90-10) :
5. Perform hyperparameter tuning using GridSearchCV (5-fold Cross validation ) on the
training dataset
6. Train the final model using the optimal hyperparameters discovered in the previous step on
the entire training dataset.
7. Test the models and generate the performance metric scores like F1-Score, Accuracy,
Precision, Recall and Confusion Matrix.
8. Draw a comparative chart on the scores obtained and interpret the performance of these
algorithms in the classification task.
9. Which algorithm works better on the given dataset?

In [ ]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import mutual_info_classif

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

import matplotlib.pyplot as plt

In [ ]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

iris = load_iris()
X = pd.DataFrame(iris.data, columns=iris.feature_names)
y = pd.Series(iris.target)

df = X.copy()
df["target"] = y

df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [ ]:
# Remove duplicates
df = df.drop_duplicates()
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [ ]:
# Remove single valued columns

single_valued_cols = [col for col in df.columns if df[col].nunique==1]
print("Single valued columns: ", single_valued_cols)
df = df.drop(columns=single_valued_cols)
df.head()

Single valued columns:  []

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [ ]:
# Separate Features and Target
X = df.drop("target", axis=1)
y = df["target"]

In [ ]:
# Normalization
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled = pd.DataFrame(X_scaled, columns=X.columns)
X_scaled.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0          -0.898033          1.012401          -1.333255         -1.308624
1          -1.139562         -0.137353          -1.333255         -1.308624
2          -1.381091          0.322549          -1.390014         -1.308624
3          -1.501855          0.092598          -1.276496         -1.308624
4          -1.018798          1.242352          -1.333255         -1.308624

In [ ]:
# Mutual Information
from sklearn.feature_selection import mutual_info_classif

mi_scores = mutual_info_classif(X_scaled, y)
mi_series = pd.Series(mi_scores, index=X.columns)

mi_series.sort_values(ascending=False)

petal length (cm)    0.982505
petal width (cm)     0.980263
sepal length (cm)    0.510199
sepal width (cm)     0.219415
dtype: float64

In [ ]:
# coorelation
df_scaled = pd.concat([X_scaled, y], axis=1)

corr_matrix = df_scaled.corr().abs()
# print(corr_matrix)

threshold = 0.9
indices = np.where(corr_matrix < threshold)
columns_to_drop = set([df_scaled.columns[i] for i, j in zip(*indices) if i < j])

print("Columns to drop: \n", columns_to_drop)

# for highly correlated..
# indices = np.where(corr_matrix > threshold)

Columns to drop:
 {'sepal length (cm)', 'sepal width (cm)'}

In [ ]:
# Train-test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3)  #70-30 split

In [ ]:
# Train models
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

classifiers = {
    "Logistic Regression": LogisticRegression(),
    "Decision Tree": DecisionTreeClassifier(),
    "Naive Bayes": GaussianNB(),
    "SVM": SVC(),
    "K-Nearest Neighbors": KNeighborsClassifier()
}

for name, classifier in classifiers.items():
    classifier.fit(X_train, y_train)

In [ ]:
# 5-fold cross validation
from sklearn.model_selection import GridSearchCV

param_grid_lr = {
'C':[0.1,1,10],
'solver':['lbfgs','liblinear']
}

grid_lr = GridSearchCV(
LogisticRegression(max_iter=1000),
param_grid_lr,
cv=5
)

grid_lr.fit(X_train,y_train)

best_lr = grid_lr.best_estimator_
best_lr

LogisticRegression(C=1, max_iter=1000)